### ISSUE TITLE
Should softmask have optional power?

### ISSUE THREAD

**Issue by faroit** [sigsep/norbert#19]
Librosa [computes](https://librosa.github.io/librosa/_modules/librosa/util/utils.html#softmask)

`M = X**power / (X**power + X_ref**power)`

I think that makes sense but of course, it may interfere with the EM algorithm

**Comment by aliutkus** [comment]
we don't need it, because it's up to the user to provide any power for his spectrogram

**Comment by faroit** [comment]
:+1:
