### ISSUE TITLE
Numerical Stability

### ISSUE THREAD

**Issue by faroit** [sigsep/norbert#20]
have we tried to fix the numerical instability by just do an elementwise minimum like...

`filter = np.minimum(filter, V)`

?

**Comment by aliutkus** [comment]
I don't understand the question. `V` is a mix spectrogram, and `filter` is what ?

**Comment by faroit** [comment]
ah yes... I was using the notation from

https://github.com/sigsep/norbert/blob/c5bf847179f6cc2b602b9383c1d5d8246debfbbf/norbert/__init__.py#L273-L277

**Comment by aliutkus** [comment]
I'm sorry, I don't understand why I should threshold `filter` (which is a ratio of spectrograms) to `V`, which is a spectrogram ? They don't live in the same space

**Comment by faroit** [comment]
okay, yes. Now I got the variables right ;-)

**Comment by faroit** [comment]
Reopen until this is fixed

**Comment by faroit** [comment]
do we still need this for the new `softmask` default?

**Comment by aliutkus** [comment]
yes, for long files it's mandatory. I see overflows when we don't
