### ISSUE TITLE
Is there a reference to this implementation?

### ISSUE THREAD

**Issue by lminer** [sigsep/norbert#22]
Is this the same MWF technique as described [here](https://ieeexplore.ieee.org/abstract/document/7952158)?

**Comment by aliutkus** [comment]
yes !
There may be small differences, in particular in the way the spatial covariance matrix is computed, to make things a bit more stable, but it's the same idea: separate first through softmask, and then fit a local Gaussian Model through EM

**Comment by faroit** [comment]
we updated the readme with more references. We will clean up everything by next week. But maybe you can get the references already
