### ISSUE TITLE
Publishing Conda package on conda-forge

### ISSUE THREAD

**Issue by Faylixe** [sigsep/norbert#26]
Hello, I just open this issue to inform you that I created and published a `Conda` package on `conda-forge` package.

The associated publishing PR is available at https://github.com/conda-forge/staged-recipes/pull/9996 and a dedicated feedstock repository has been created at https://github.com/conda-forge/norbert-feedstock.

If you want to be added as maintainer please tell me :).

Regard

**Comment by faroit** [comment]
thats great. thanks! I am not using conda much, so I am fine with someone else maintaining the package.
