### ISSUE TITLE
Problem using the residual model

### ISSUE THREAD

**Issue by romanbsd** [sigsep/norbert#29]
I think that I followed the documentation closely, but I'm failing to get some decent results with the  residual_model + wiener.
Basically I took a background music track, and added another source using `sox -m`. Then I'm feeding the mix and the background track to my script and expect to extract the added source.
This is a script I'm using for separation, but it doesn't seem to work well.
Please advise...

```python
#!/usr/bin/env python3
import sys
import librosa
import norbert
import numpy as np
from scipy.io import wavfile

sr = 48000
n_fft = 4096
hop = 512
mono = True


def to_short(y):
    norm = np.abs(y).max()
    y /= norm
    return (y * 32767).astype(np.int16)


def separate(mix, src):
    X = librosa.stft(mix, n_fft=n_fft, hop_length=hop, center=False).T
    V = librosa.stft(src, n_fft=n_fft, hop_length=hop, center=False).T

    # 1 channel dimension
    X = np.expand_dims(X, -1)
    # 1 channel dimension
    V = np.expand_dims(V, -1)
    # 1 source dimension
    V = np.expand_dims(V, -1)

    print('X shape', X.shape)
    print('V shape', V.shape)

    # v: (nb_frames, nb_bins, {1, nb_channels}, nb_sources)
    # x: (nb_frames, nb_bins, nb_channels)
    V = norbert.residual_model(V, X, alpha=1)
    print('V shape (w/residual)', V.shape)
    Y = norbert.wiener(V, X.astype(np.complex128),
                       iterations=1, use_softmask=False)
    print('Y shape', Y.shape)

    Y = np.squeeze(Y[..., 1]).T
    print('Y shape', Y.shape)
    y = librosa.istft(Y, hop_length=hop, win_length=n_fft)

    return y


if __name__ == '__main__':
    mix, _ = librosa.load(sys.argv[1], sr=sr, mono=mono, duration=30)
    src, _ = librosa.load(sys.argv[2], sr=sr, mono=mono, duration=30)
    print('Input shape:', mix.shape)
    output = separate(mix, src)
    print('Output shape:', output.shape)
    wavfile.write('out.wav', sr, to_short(output))

```
Thank you in advance.

**Comment by romanbsd** [comment]
Ok, I figured that out. The V should be magnitude (e.g. np.abs()) where the X should be complex (as it is).

**Comment by faroit** [comment]
@romanbsd 👍 if there is anything we could do to improve the docs. let us know

**Comment by romanbsd** [comment]
I think that it should state that V is either magnitudes or power, and maybe issue a warning if V is a complex type.

**Comment by faroit** [comment]
good point. @aliutkus do you agree?

**Comment by aliutkus** [comment]
hi @romanbsd, thanks for the feedback
the confusion maybe arises from a misunderstanding of the word "spectrogram", that is defined as a magnitude (or fractional magnitude) of the STFT
maybe we can indeed make this more explicit in the docs?
best

**Comment by romanbsd** [comment]
I was confused because expected that both function parameters are of the same units, and because while spectrogram is defined as: "A spectrogram is a visual representation of the spectrum of frequencies of a signal as it varies with time." as per Wikipedia, some people use this word interchangeably with STFT. Thus, to avoid confusion I'd add it to documentation, and, perhaps add a warning when it's complex.
