### ISSUE TITLE
Is there a way to implement Wiener filter in real-time?

### ISSUE THREAD

**Issue by satvik-venkatesh** [sigsep/norbert#32]
Thank you for this great project. I was wondering if there was a way to implement Wiener filters in real-time? In this case, nb_frames=1. I am using the Open-Unmix model, but I don't get a meaningful output when I set wiener window length to 1. Thank you.

**Comment by faroit** [comment]
Hi @satvik-venkatesh, I don't think that would give you any good results. You might want to implement some lookahead window 

@aliutkus

**Comment by satvik-venkatesh** [comment]
Hi @faroit . Ah I see, that is helpful. Thank you very much for the clarification!
